# Generated by Django 4.2.5 on 2023-09-20 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserProfileInfo",
        ),
    ]
